print ('Guess the number!')
print('Enter the limit: 10')
print('I am thinking of a number from 1 to 10')
print('Your guess: 5')
print('Too low guess again: 7')
print('Still too low try again: 10')
print('You guessed it in 3 tries.')

print('Would you like to play again? (y/n): y')
print('I am thinking of a number from 1 to 20')
print('Your guess: 20')
print('Too high guess again: 10')
print('Too low this time: 11')
print('Wow you guessed it in 3 tries')
print('Would you like to play again? (y/n): n')
print('Bye!')